### ISSUE TITLE
Heading depth

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/machine-learning#2]
Use level 1 headings on top of each page. They should match the heading given in the table of contents. All other headings should be level 2 (`##`).

**Comment by dhinstitutes** [comment]
I went through the files and have created a bunch of patches that should be fairly easy for @rachelrakov to pull in to the final project now. I hope that solves it!

**Comment by kallewesterling** [comment]
Weird - I can't see any of the patches I made any longer. Ah! I wonder if I have to go over everything again! :/

**Comment by smythp** [comment]
If the PRs are giving you a headache I think it's OK to go ahead and make commits. Looks like that's what you might be doing.

**Comment by kallewesterling** [comment]
Yeah, I think it was because I wasn't added as a collaborator on the People tab. Now I can commit changes, which I couldn't a week ago! :)

**Comment by kallewesterling** [comment]
I believe this should all have been fixed now!

**Comment by kallewesterling** [comment]
I will go head and close this issue now. Reopen if needed, @smythp!
