### ISSUE TITLE
Saving file fails

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/machine-learning#28]
In [Getting Our Data > What if we want to visualize that information?](https://github.com/DHRI-Curriculum/machine-learning/blob/master/sections/data.md#what-if-we-want-to-visualize-that-information), this command fails:

``fig.savefig("images/categories_counts.png", bbox_inches = 'tight', pad_inches = 0)``

This happens if the learner does not have an `images` directory where the script is run. Perhaps it needs some clarification?

**Comment by kallewesterling** [comment]
Addressed in ff22d44e8eaffc5ab9a72893b04d1812303a911f. Feel free to edit or revert.

**Comment by story645** [comment]
It might just be easier to do

`fig.savefig("categories_counts.png", bbox_inches = 'tight', pad_inches = 0)`
