### ISSUE TITLE
Meaningful alt text

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/machine-learning#4]
In our meeting we disucssed adding meaningful alt text for screen reader uses (or fallback  users) that describes what the images depict. Looks like this still needs to be done.

**Comment by rachelrakov** [comment]
Are you sure that you have the new markdown files?  Perhaps I uploaded the wrong ones?  This was already done - I'm not sure why you aren't able to see it.

**Comment by dhinstitutes** [comment]
I looked quickly through the files and it looks good to me as well but maybe you've been able to find anything in particular that we can't seem to find, @smythp? I know it was long ago that you posted the issue but do you have any memory of where you saw the missing alt-text? I want to make sure we don't miss this!

**Comment by dhinstitutes** [comment]
I looked quickly through the files and it looks good to me as well but maybe you've been able to find anything in particular that we can't seem to find, @smythp? I know it was long ago that you posted the issue but do you have any memory of where you saw the missing alt-text? I want to make sure we don't miss this!

**Comment by smythp** [comment]
Think this was based on an upload of the wrong files. Closing.

**Comment by smythp** [comment]
Actually this isn't resolved. The tables only have one-word alt text, as in intro_to_ml_with_python.md that has this line:

    ![fruit3](images/fruit3.png)

The text in square brackets should describe as best as can be managed the information the table is conveying, i.e. think about why the table is there rhetorically and convey that in words rather than describe the table in a very literal way.

**Comment by smythp** [comment]
For example, on that same page "Getting Our Data" would be an example of a good heading.

**Comment by kallewesterling** [comment]
@rachelrakov When you revise the repo, do you mind having a look at the alt text for tables/images for accessibility?

**Comment by rachelrakov** [comment]
Will do!

**Comment by kallewesterling** [comment]
Thank you!!

**Comment by kallewesterling** [comment]
Checked across all the sections and it seems that all the alt texts are updated now so I'll close this issue.
