### ISSUE TITLE
Very long headings

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/machine-learning#5]
Looks like there are still a few headings in here that are very long, i.e. are standing in for normal text. Replace with shorter headings and make these headings into normal text.

**Comment by dhinstitutes** [comment]
Looks like this issue was fixed, is that correct @smythp?

**Comment by smythp** [comment]
There seem to still be examples of this in the text:

    Get the sentences from each corpus

and 

    Take a look at the first 5 sentences in each corpus

would be examples of headings that should be normal text, and group under a different descriptive heading, in `classification.md`, which you can view here:

https://github.com/DHRI-Curriculum/machine-learning/blob/master/sections/classification.md

**Comment by dhinstitutes** [comment]
I see what you're saying. Yes, this needs some editing. @rachelrakov - do you want to take a stab at this?

**Comment by rachelrakov** [comment]
Won’t be able to get to this this weekend, I am out of town.  I’ll take a look early next week?

**Comment by kallewesterling** [comment]
Great @rachelrakov - whenever you have a chance in the next week sounds great! Just want to make sure we all keep finishing the curriculum on our radar! :)

**Comment by kallewesterling** [comment]
Just a quick check-in on this thread. @rachelrakov, Lisa told me that you are quite busy right now. Not to stress you out but it would be great if I could have a date when we think this repo will be ready for Gitbook "production" - do you think end of the semester would work? January? (This is also in regards to #4.)

**Comment by kallewesterling** [comment]
I fixed most of the things that I think needed some fixing. Take a look if you want and feel free to change things around.
