### ISSUE TITLE
change file names to reflect ordering

### ISSUE THREAD

**Issue by story645** [DHRI-Curriculum/machine-learning#6]
add prefix for files with numbers so somebody can just scan the .md files for the right order.

**Comment by dhinstitutes** [comment]
I have gone through the project and created patches for all of these renaming of files and top/bottom navigation links. However, I haven't looked through the text, so a read-through for correct links would probably be a good thing once those patches have been accepted.

**Comment by smythp** [comment]
Most of the other sessions don't have this prefix. I think this will cause more problems then it fixes and I've found the numbering needs to be changed in editing a lot anyway. I'd just cancel the PR and leave it as is, I'll close this issue. Sorry that you took the time to proactively make the edits.
